### ISSUE TITLE
Please upload a jar file suitable for gitbucket v4.20 or later

### ISSUE THREAD

**Issue by sho-suzuki** [codelibs/gitbucket-fess-plugin#17]
Hi.
I'd like to use this plugin with gitbucket v4.20.
I downloaded v1.2 jar file from release page, but it didn't work.
Could you upload a new jar file suitable for gitbucket v4.20 or later.
thank you!

**Comment by marevol** [comment]
Released 1.3.

**Comment by sho-suzuki** [comment]
thank you!
Could you upload jar file to release page?

**Comment by kw-udon** [comment]
I just released in GitHub release page.
You can also obtain jar files from [codelib's maven repository](http://central.maven.org/maven2/org/codelibs/gitbucket/gitbucket-fess-plugin_2.12).

**Comment by sho-suzuki** [comment]
@kw-udon thanks!
the version of fess plugin displayed 1.2.0 in gitbucket page. but it works with gitbucket v4.20.

**Comment by kw-udon** [comment]
Thank you for reporting.
This is probably because we forgot updating the version description [here](https://github.com/codelibs/gitbucket-fess-plugin/blob/master/src/main/scala/Plugin.scala#L14).
We will fix it later.

**Comment by kw-udon** [comment]
I fixed the version description by c53d7575bdd09571debb509f5c8a3b4642ddd1ce.
