### ISSUE TITLE
Search results are garbled.

### ISSUE THREAD

**Issue by sho-suzuki** [codelibs/gitbucket-fess-plugin#18]
# plugin version
1.3
# gitbucket version
4.20
# what is matter
If search result has multi byte string(like a japanese string), It displayed with garbled string. 

![image](https://user-images.githubusercontent.com/512636/35669089-4a813244-0777-11e8-8481-b2bea261c6cf.png)

**Comment by kw-udon** [comment]
Fixed by c9d2b7488bf2290467f6dabab21f38a5c99884e5. Thanks!

**Comment by sho-suzuki** [comment]
- pull repository
- sbt package
-> build v1.3.1 plugin
- v1.3.1 plugin put to plugins dir
- gitbucket reload
 
that's works fine!
thank you!
