### ISSUE TITLE
[question] Is it possible to index multiple branches?

### ISSUE THREAD

**Issue by heldbrendel** [codelibs/gitbucket-fess-plugin#21]
I followed the instruction to setup the plugin together with fess and the search works for the master branch of my repositories. Is it possible to let the plugin also index other branches then the master branch? I am asking, because i could not find information about something like that in the readme.

gitbucket: 4.21.2
gitbucket-fess-plugin: 1.3.0
fess: 12.1.0

**Comment by kw-udon** [comment]
> Is it possible to index multiple branches?

No. Fess stores codes only in the "default branch" of each repositories.

You can change the default branch of each repository on GitBucket's setting page:
"Settings > Branches > Default branch"
