### ISSUE TITLE
What kind of information can be searched for?

### ISSUE THREAD

**Issue by uli-heller** [codelibs/gitbucket-fess-plugin#5]
* Names of files checked in any git repo?
* Contents of files checked in any git repo?
* Historical names and/or contents?
* Commit comments?
* Commit modifications?
* Similar for wiki pages?
* Similar for  issues?
* Similar for pull requests?
* Similar for user names and bios?
* Similar for repository names and descriptions?

Currently, I'm only just curious. I'm not sure if all of this makes sense...

**Comment by kw-udon** [comment]
**Already supported**
* Names of files
* Contents of files

**Will be supported in the major version**
* Title and contents of wiki pages
* Title and comments of issues / pull requests

---

We may support other information (e.g. user names, repository names, etc) in the future.

**Comment by kw-udon** [comment]
Search by repository names is already supported by GitBucket. (It slipped my mind.)
It responds fast enough. Thus, our repository doesn't have to support it.

**Comment by kw-udon** [comment]
I implemented the search functionality for [issues](https://github.com/codelibs/gitbucket-fess-plugin/commit/f79daa7ca1248d098f9acbffc04acc519524b9cb) and [wiki pages](https://github.com/codelibs/gitbucket-fess-plugin/commit/2491cc0da77957fc6d658af84a6fd07a3a523124).
