### ISSUE TITLE
expose gitbucket-fess-plugin in github releases

### ISSUE THREAD

**Issue by McFoggy** [codelibs/gitbucket-fess-plugin#7]
In order to allow automatic download for [gitbucket-community.herokuapp.com](https://github.com/gitbucket-plugins/gitbucket-community.herokuapp.com) it would be convenient that you upload the jar corresponding to your release under your [github release section](https://github.com/codelibs/gitbucket-fess-plugin/releases).

**Comment by marevol** [comment]
We will put plugin jar to github from next releases.

**Comment by McFoggy** [comment]
@marevol I do not want to enforce you a way of working ; if you push to another kind of repository like maven central it is also OK for me. I just need to know to be able to download from somewhere.

**Comment by marevol** [comment]
Jar files are in Maven Central.
Please see https://github.com/codelibs/gitbucket-fess-plugin#release

**Comment by McFoggy** [comment]
ok then keep it like that it is enough for external download.

**Comment by kw-udon** [comment]
@McFoggy
We published the first major version release and uploaded the jar on [GitHub's release page](https://github.com/codelibs/gitbucket-fess-plugin/releases).

Regards,
